server:
  address: localhost
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/capstone2
    username: capstone_user
    password: hatecapstone!@

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: LVNOGVmIy9FHnH0_Inhf
            client-secret: aevYbPoXlj
            redirect-uri: "{baseUrl}/login/callback/naver"
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - profile
            client-name: Naver
          kakao:
            client-id: a5cf0d24bf27a526c91f251eb7586051
            client-secret: C16R5Mv44VWmkk4wpsuCefRrPThndiwL
            redirect-uri: "{baseUrl}/login/callback/kakao"
            authorization-grant-type: authorization_code
            client-name: Kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id